import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { UserProvider } from '@auth0/nextjs-auth0/client';
import { getSession } from '@auth0/nextjs-auth0';
import { redirect } from 'next/navigation';
import { cn } from '@/utils/cn';
import PopupMenu from './popupMenu';
import { isAdmin } from '@/utils/roles';
import Unauthorized from './unauthorized';
import { getUserByEmail } from '@/db/users/getUsers';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getSession();
  const user = await getUserByEmail(session?.user.email);

  return (
    <html lang="en">
      <UserProvider>
        <body className={cn(inter.className)}>
          {user ? children : <Unauthorized />}
          {isAdmin(session) && <PopupMenu className="absolute top-4 right-4" />}
        </body>
      </UserProvider>
    </html>
  );
}
